discord:
  enabled: false

dashboard:
  demo: true
  password-hash: $2a$12$Y.nj4APXYjOlmo3Y6yc0deCc.WnkAZxU3z550F3/7j4BnKHcUqtxK
  max-login-attempts: 5
  lockout-duration-minutes: 15

spring:
  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        cache: false